[project]
name = "AdventOfCode"
version = "0.1.0"
requires-python = ">=3.14"
authors = [{ name = "Dmitry Volodin", email = "mr.molkree@gmail.com" }]
readme = "README.md"


[dependency-groups]
dev = [
    "black==26.1.0",
    "flake8==7.3.0",
    "isort==8.0.0",
    "mypy==1.19.1",
    "pep8-naming==0.15.1",
    "prek==0.3.3",
]
